#!/usr/bin/env bash
# configures server to listen pn port 80 of all servers active IPv4 IPs
sudo sed -i "s/8080/80/" /etc/nginx/sites-enabled/default
sudo service nginx restart
echo "nginx is not running" | sudo dd status=none of=/run/nginx.pid
